### ISSUE TITLE
how can i build into vs

### ISSUE THREAD

**Issue by NandyShi** [chronoxor/CppTrader#1]
cd build
vs.bat
i can not find where vs.bat is. should you help me

**Comment by chronoxor** [comment]
First you have to setup gil (git links) tool - https://github.com/chronoxor/gil#setup

Than Setup repository with gil (git links) tool:
```
git clone https://github.com/chronoxor/CppTrader.git
cd CppTrader
gil update
```

As the result [build scripts](https://github.com/chronoxor/CppBuildScripts) will appear in `build` directory.
