### ISSUE TITLE
Validate trailing order

### ISSUE THREAD

**Issue by yueliangwen** [chronoxor/CppTrader#11]
![image](https://user-images.githubusercontent.com/1107708/74083558-841df500-4aa0-11ea-89b2-8727fc145495.png)

At order.cpp: 83, is the -1000 validation number exactly?

**Comment by chronoxor** [comment]
According to the spec in `include\trader\matching\order.h:180`:
```
        Positive value represents absolute distance from the market.
        Negative value represents percentage distance from the market
        with 0.01% precision (-1 means 0.01, -10000 means 100%).
```

Therefore validation rules restricts -1000 <= TrailingDistance <= -1 in case of 0.01% precision.
