### ISSUE TITLE
Error with HdrHistogram

### ISSUE THREAD

**Issue by mathsCode** [chronoxor/CppTrader#13]
/CppTrader/modules/CppBenchmark/modules/HdrHistogram/src/hdr_histogram_log.c:36:9: 
error: 
unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma ide diagnostic ignored "readability-redundant-declaration"

**Comment by chronoxor** [comment]
https://github.com/HdrHistogram/HdrHistogram_c/issues/85

**Comment by mathsCode** [comment]
It is fixed now. Thanks.
