### ISSUE TITLE
Segfault for ./cpptrader-performance-market_manager_optimized on 01302020.NASDAQ_ITCH50

### ISSUE THREAD

**Issue by DaemonSnake** [chronoxor/CppTrader#14]
The market_manager_optimized version of the binary segfaults with 01302020.NASDAQ_ITCH50

![segfault](https://user-images.githubusercontent.com/11693483/86040242-fab59200-ba43-11ea-95a6-870c45e32aca.png)

**Comment by DaemonSnake** [comment]
same for the aggressive version

**Comment by kylelee** [comment]
could you post the itch file here ?
