### ISSUE TITLE
Two test failures 

### ISSUE THREAD

**Issue by m-mani** [chronoxor/CppTrader#17]
===============================================================================
test cases:  18 |  16 passed | 2 failed
assertions: 151 | 149 passed | 2 failed

**Comment by m-mani** [comment]
More color: 

due to unexpected exception with message:
  File system exception: Cannot create a new file!
  System error: 2
  System message: No such file or directory
  Source location: /CppTrader/modules/CppCommon/source/filesystem/file.cpp:239

**Comment by chronoxor** [comment]
Fixed File move operation in CppCommon module. Please try again after `gil pull` command to update sources.

**Comment by m-mani** [comment]
Works well, Thank you.
