### ISSUE TITLE
./01-generate.sh: line 6: cmake: command not found

### ISSUE THREAD

**Issue by andrenorman** [chronoxor/CppTrader#26]
Hello,

I just cloned the project and followed the steps to build the project. I'm on macOS and run the command `./unix.sh` inside the build folder which produces an error: `./01-generate.sh: line 6: cmake: command not found`

Any ideas on what could be going on?

Thanks

**Comment by chronoxor** [comment]
![image](https://user-images.githubusercontent.com/4397805/149338385-f8710ab2-6333-4f03-bda6-7417b95fdbd1.png)

**Comment by andrenorman** [comment]
@chronoxor thanks for the quick response. Those commands were previously run.
![image](https://user-images.githubusercontent.com/3009846/149339657-3b5d5bcb-884c-4ffd-8c95-e6b0361e78ea.png)

**Comment by chronoxor** [comment]
![image](https://user-images.githubusercontent.com/4397805/149340513-5706b3dd-103b-4bdf-b94a-bb635795819f.png)

**Comment by chronoxor** [comment]
CMake is also pre-required - https://cmake.org/download/

**Comment by andrenorman** [comment]
Thanks @chronoxor, installing cmake solved the issue.
