### ISSUE TITLE
Decimal value

### ISSUE THREAD

**Issue by gennadylokal** [chronoxor/CppTrader#27]
Hello @chronoxor 

I want to know why the price and quantity don't have a decimal value, is there any particular concern? is there any problem if I change it to decimal value?

Thank you in advance.

**Comment by chronoxor** [comment]
1) Performance
2) Precision loss for float data types in [money calculations](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency)
3) There is no Decimal data type out of box in C++ compilers without using heavy [third-party libs](https://stackoverflow.com/a/64606530)

**Comment by welly87** [comment]
so basically we need to convert decimal (dollar) into decicents or something? @chronoxor
