### ISSUE TITLE
What Is The Best Way to Get Status of Taker or Maker at "onExecutedOrder" ?

### ISSUE THREAD

**Issue by devararendy** [chronoxor/CppTrader#30]
Dear @chronoxor 

I would like to ask :
1. What is the best way to get status of Taker or Maker order at callback "onExecutedOrder" ?
In my case, i need to know which order is Taker / Maker.
2. What is the best way to get the Match Number of the Executed Orders, so we can know which order is matching with the other order.

Thank You very much for Your Great repo
Have a nice day

Best Regards

Rendy

**Comment by joyfulcat** [comment]
Hello, 

How did you end up going about this? 

Thanks!
