### ISSUE TITLE
Trailing Stop Limit Seems Only Work One Time, For Second Time With Same Scenario Is not Executed

### ISSUE THREAD

**Issue by devararendy** [chronoxor/CppTrader#31]
Dear @chronoxor 

i'm using cpptrader-example-matching_engine from commit [43b8cfbc438373d3fb9b784025f6018f453e4e72](https://github.com/chronoxor/CppTrader/commit/43b8cfbc438373d3fb9b784025f6018f453e4e72)

I have a Trailing Stop Limit Scenario as shown below :

add symbol 1 BTC_ETH
add book 1
enable matching

add limit sell 1 1 1000 100
add limit sell 2 1 1100 100
add limit sell 3 1 1100 100
add limit buy 4 1 900 100
add trailing stop-limit sell 5 1 700 700 100 100 0
add limit buy 6 1 1000 100
add limit buy 7 1 1100 100
add limit sell 8 1 900 100
add limit buy 9 1 1100 200

At first attempt the Trailing Stop is working and Executed. But When I retry with same scenario (without re-running the executable) the Trailing Stop Limit is not working. And why SellStop value is so big ?: 

add limit sell 1 1 1000 100
add limit sell 2 1 1100 100
add limit sell 3 1 1100 100
add limit buy 4 1 900 100
add trailing stop-limit sell 5 1 700 700 100 100 0
add limit buy 6 1 1000 100
add limit buy 7 1 1100 100
add limit sell 8 1 900 100
add limit buy 9 1 1100 200

I will attach the screen shot also to make it easier to see / debug

1. First Attempt and Trailing Stop is working
![image](https://user-images.githubusercontent.com/22151076/159837428-6fbe8759-2ab6-4061-b20a-135be74e7d73.png)

2. Second Attempt with same scenario Trailing Stop is not working (without rerunning the executable)
![image](https://user-images.githubusercontent.com/22151076/159837584-c6c4141f-c77b-4c92-9676-c49d48353020.png)

Thank You very much 
Have a nice day

Best Regards

**Comment by chronoxor** [comment]
Fixed! Thanks for reporting!
