### ISSUE TITLE
NASDAQ ITCH sample data source is unavailable

### ISSUE THREAD

**Issue by hyili** [chronoxor/CppTrader#32]
Hi,
I'm new to C++ trading system. Found this great project for learning.
When I tried to build and run the sample benchmark, I found that I can't access to the ftp://emi.nasdaq.com/ITCH to get the ITCH sample data. After spending some time on this, I finally found out **https://emi.nasdaq.com/ITCH** is a replacement.
Maybe this could help, for someone who also need the sample data.

thank you.

**Comment by Reidmen** [comment]
This is a bit late, but a PR would be ideal, [data is here](https://emi.nasdaq.com/ITCH/Nasdaq%20ITCH/) will be proposing one PR to fix it.

**Comment by chronoxor** [comment]
Fixed, thanks!
